// Code generated by abigen. DO NOT EDIT.
// This file is a generated binding and any manual changes will be lost.

package contracts

import (
	"fmt"
	"math/big"
	"reflect"
	"strings"

	ethereum "github.com/erigontech/erigon"
	"github.com/erigontech/erigon-lib/abi"
	"github.com/erigontech/erigon-lib/common"
	"github.com/erigontech/erigon-lib/types"
	"github.com/erigontech/erigon-p2p/event"
	"github.com/erigontech/erigon/execution/abi/bind"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
	_ = fmt.Errorf
	_ = reflect.ValueOf
)

// VictionRandomizeABI is the input ABI used to generate the binding from.
const VictionRandomizeABI = "[{\"constant\":true,\"inputs\":[{\"name\":\"_validator\",\"type\":\"address\"}],\"name\":\"getSecret\",\"outputs\":[{\"name\":\"\",\"type\":\"bytes32[]\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":false,\"inputs\":[{\"name\":\"_secret\",\"type\":\"bytes32[]\"}],\"name\":\"setSecret\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[{\"name\":\"_validator\",\"type\":\"address\"}],\"name\":\"getOpening\",\"outputs\":[{\"name\":\"\",\"type\":\"bytes32\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":false,\"inputs\":[{\"name\":\"_opening\",\"type\":\"bytes32\"}],\"name\":\"setOpening\",\"outputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[],\"payable\":false,\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"}]"

// VictionRandomizeBin is the compiled bytecode used for deploying new contracts.
var VictionRandomizeBin = "0x6060604052341561000f57600080fd5b6103368061001e6000396000f3006060604052600436106100615763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663284180fc811461006657806334d38600146100d8578063d442d6cc14610129578063e11f5ba21461015a575b600080fd5b341561007157600080fd5b610085600160a060020a0360043516610170565b60405160208082528190810183818151815260200191508051906020019060200280838360005b838110156100c45780820151838201526020016100ac565b505050509050019250505060405180910390f35b34156100e357600080fd5b61012760046024813581810190830135806020818102016040519081016040528093929190818152602001838360200280828437509496506101f395505050505050565b005b341561013457600080fd5b610148600160a060020a0360043516610243565b60405190815260200160405180910390f35b341561016557600080fd5b61012760043561025e565b61017861028e565b60008083600160a060020a0316600160a060020a031681526020019081526020016000208054806020026020016040519081016040528092919081815260200182805480156101e757602002820191906000526020600020905b815481526001909101906020018083116101d2575b50505050509050919050565b610384430661032081101561020757600080fd5b610352811061021557600080fd5b600160a060020a033316600090815260208190526040902082805161023e9291602001906102a0565b505050565b600160a060020a031660009081526001602052604090205490565b610384430661035281101561027257600080fd5b50600160a060020a033316600090815260016020526040902055565b60206040519081016040526000815290565b8280548282559060005260206000209081019282156102dd579160200282015b828111156102dd57825182556020909201916001909101906102c0565b506102e99291506102ed565b5090565b61030791905b808211156102e957600081556001016102f3565b905600a165627a7a7230582034991c8dc4001fc254f3ba2811c05d2e7d29bee3908946ca56d1545b2c852de20029"

// DeployVictionRandomize deploys a new Ethereum contract, binding an instance of VictionRandomize to it.
func DeployVictionRandomize(auth *bind.TransactOpts, backend bind.ContractBackend) (common.Address, types.Transaction, *VictionRandomize, error) {
	parsed, err := abi.JSON(strings.NewReader(VictionRandomizeABI))
	if err != nil {
		return common.Address{}, nil, nil, err
	}

	address, tx, contract, err := bind.DeployContract(auth, parsed, common.FromHex(VictionRandomizeBin), backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, &VictionRandomize{VictionRandomizeCaller: VictionRandomizeCaller{contract: contract}, VictionRandomizeTransactor: VictionRandomizeTransactor{contract: contract}, VictionRandomizeFilterer: VictionRandomizeFilterer{contract: contract}}, nil
}

// VictionRandomize is an auto generated Go binding around an Ethereum contract.
type VictionRandomize struct {
	VictionRandomizeCaller     // Read-only binding to the contract
	VictionRandomizeTransactor // Write-only binding to the contract
	VictionRandomizeFilterer   // Log filterer for contract events
}

// VictionRandomizeCaller is an auto generated read-only Go binding around an Ethereum contract.
type VictionRandomizeCaller struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// VictionRandomizeTransactor is an auto generated write-only Go binding around an Ethereum contract.
type VictionRandomizeTransactor struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// VictionRandomizeFilterer is an auto generated log filtering Go binding around an Ethereum contract events.
type VictionRandomizeFilterer struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// VictionRandomizeSession is an auto generated Go binding around an Ethereum contract,
// with pre-set call and transact options.
type VictionRandomizeSession struct {
	Contract     *VictionRandomize // Generic contract binding to set the session for
	CallOpts     bind.CallOpts     // Call options to use throughout this session
	TransactOpts bind.TransactOpts // Transaction auth options to use throughout this session
}

// VictionRandomizeCallerSession is an auto generated read-only Go binding around an Ethereum contract,
// with pre-set call options.
type VictionRandomizeCallerSession struct {
	Contract *VictionRandomizeCaller // Generic contract caller binding to set the session for
	CallOpts bind.CallOpts           // Call options to use throughout this session
}

// VictionRandomizeTransactorSession is an auto generated write-only Go binding around an Ethereum contract,
// with pre-set transact options.
type VictionRandomizeTransactorSession struct {
	Contract     *VictionRandomizeTransactor // Generic contract transactor binding to set the session for
	TransactOpts bind.TransactOpts           // Transaction auth options to use throughout this session
}

// VictionRandomizeRaw is an auto generated low-level Go binding around an Ethereum contract.
type VictionRandomizeRaw struct {
	Contract *VictionRandomize // Generic contract binding to access the raw methods on
}

// VictionRandomizeCallerRaw is an auto generated low-level read-only Go binding around an Ethereum contract.
type VictionRandomizeCallerRaw struct {
	Contract *VictionRandomizeCaller // Generic read-only contract binding to access the raw methods on
}

// VictionRandomizeTransactorRaw is an auto generated low-level write-only Go binding around an Ethereum contract.
type VictionRandomizeTransactorRaw struct {
	Contract *VictionRandomizeTransactor // Generic write-only contract binding to access the raw methods on
}

// NewVictionRandomize creates a new instance of VictionRandomize, bound to a specific deployed contract.
func NewVictionRandomize(address common.Address, backend bind.ContractBackend) (*VictionRandomize, error) {
	contract, err := bindVictionRandomize(address, backend, backend, backend)
	if err != nil {
		return nil, err
	}
	return &VictionRandomize{VictionRandomizeCaller: VictionRandomizeCaller{contract: contract}, VictionRandomizeTransactor: VictionRandomizeTransactor{contract: contract}, VictionRandomizeFilterer: VictionRandomizeFilterer{contract: contract}}, nil
}

// NewVictionRandomizeCaller creates a new read-only instance of VictionRandomize, bound to a specific deployed contract.
func NewVictionRandomizeCaller(address common.Address, caller bind.ContractCaller) (*VictionRandomizeCaller, error) {
	contract, err := bindVictionRandomize(address, caller, nil, nil)
	if err != nil {
		return nil, err
	}
	return &VictionRandomizeCaller{contract: contract}, nil
}

// NewVictionRandomizeTransactor creates a new write-only instance of VictionRandomize, bound to a specific deployed contract.
func NewVictionRandomizeTransactor(address common.Address, transactor bind.ContractTransactor) (*VictionRandomizeTransactor, error) {
	contract, err := bindVictionRandomize(address, nil, transactor, nil)
	if err != nil {
		return nil, err
	}
	return &VictionRandomizeTransactor{contract: contract}, nil
}

// NewVictionRandomizeFilterer creates a new log filterer instance of VictionRandomize, bound to a specific deployed contract.
func NewVictionRandomizeFilterer(address common.Address, filterer bind.ContractFilterer) (*VictionRandomizeFilterer, error) {
	contract, err := bindVictionRandomize(address, nil, nil, filterer)
	if err != nil {
		return nil, err
	}
	return &VictionRandomizeFilterer{contract: contract}, nil
}

// bindVictionRandomize binds a generic wrapper to an already deployed contract.
func bindVictionRandomize(address common.Address, caller bind.ContractCaller, transactor bind.ContractTransactor, filterer bind.ContractFilterer) (*bind.BoundContract, error) {
	parsed, err := abi.JSON(strings.NewReader(VictionRandomizeABI))
	if err != nil {
		return nil, err
	}
	return bind.NewBoundContract(address, parsed, caller, transactor, filterer), nil
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_VictionRandomize *VictionRandomizeRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _VictionRandomize.Contract.VictionRandomizeCaller.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_VictionRandomize *VictionRandomizeRaw) Transfer(opts *bind.TransactOpts) (types.Transaction, error) {
	return _VictionRandomize.Contract.VictionRandomizeTransactor.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_VictionRandomize *VictionRandomizeRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (types.Transaction, error) {
	return _VictionRandomize.Contract.VictionRandomizeTransactor.contract.Transact(opts, method, params...)
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_VictionRandomize *VictionRandomizeCallerRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _VictionRandomize.Contract.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_VictionRandomize *VictionRandomizeTransactorRaw) Transfer(opts *bind.TransactOpts) (types.Transaction, error) {
	return _VictionRandomize.Contract.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_VictionRandomize *VictionRandomizeTransactorRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (types.Transaction, error) {
	return _VictionRandomize.Contract.contract.Transact(opts, method, params...)
}

// GetOpening is a free data retrieval call binding the contract method 0xd442d6cc.
//
// Solidity: function getOpening(address _validator) view returns(bytes32)
func (_VictionRandomize *VictionRandomizeCaller) GetOpening(opts *bind.CallOpts, _validator common.Address) ([32]byte, error) {
	var out []interface{}
	err := _VictionRandomize.contract.Call(opts, &out, "getOpening", _validator)

	if err != nil {
		return *new([32]byte), err
	}

	out0 := *abi.ConvertType(out[0], new([32]byte)).(*[32]byte)

	return out0, err

}

// GetOpening is a free data retrieval call binding the contract method 0xd442d6cc.
//
// Solidity: function getOpening(address _validator) view returns(bytes32)
func (_VictionRandomize *VictionRandomizeSession) GetOpening(_validator common.Address) ([32]byte, error) {
	return _VictionRandomize.Contract.GetOpening(&_VictionRandomize.CallOpts, _validator)
}

// GetOpening is a free data retrieval call binding the contract method 0xd442d6cc.
//
// Solidity: function getOpening(address _validator) view returns(bytes32)
func (_VictionRandomize *VictionRandomizeCallerSession) GetOpening(_validator common.Address) ([32]byte, error) {
	return _VictionRandomize.Contract.GetOpening(&_VictionRandomize.CallOpts, _validator)
}

// GetSecret is a free data retrieval call binding the contract method 0x284180fc.
//
// Solidity: function getSecret(address _validator) view returns(bytes32[])
func (_VictionRandomize *VictionRandomizeCaller) GetSecret(opts *bind.CallOpts, _validator common.Address) ([][32]byte, error) {
	var out []interface{}
	err := _VictionRandomize.contract.Call(opts, &out, "getSecret", _validator)

	if err != nil {
		return *new([][32]byte), err
	}

	out0 := *abi.ConvertType(out[0], new([][32]byte)).(*[][32]byte)

	return out0, err

}

// GetSecret is a free data retrieval call binding the contract method 0x284180fc.
//
// Solidity: function getSecret(address _validator) view returns(bytes32[])
func (_VictionRandomize *VictionRandomizeSession) GetSecret(_validator common.Address) ([][32]byte, error) {
	return _VictionRandomize.Contract.GetSecret(&_VictionRandomize.CallOpts, _validator)
}

// GetSecret is a free data retrieval call binding the contract method 0x284180fc.
//
// Solidity: function getSecret(address _validator) view returns(bytes32[])
func (_VictionRandomize *VictionRandomizeCallerSession) GetSecret(_validator common.Address) ([][32]byte, error) {
	return _VictionRandomize.Contract.GetSecret(&_VictionRandomize.CallOpts, _validator)
}

// SetOpening is a paid mutator transaction binding the contract method 0xe11f5ba2.
//
// Solidity: function setOpening(bytes32 _opening) returns()
func (_VictionRandomize *VictionRandomizeTransactor) SetOpening(opts *bind.TransactOpts, _opening [32]byte) (types.Transaction, error) {
	return _VictionRandomize.contract.Transact(opts, "setOpening", _opening)
}

// SetOpening is a paid mutator transaction binding the contract method 0xe11f5ba2.
//
// Solidity: function setOpening(bytes32 _opening) returns()
func (_VictionRandomize *VictionRandomizeSession) SetOpening(_opening [32]byte) (types.Transaction, error) {
	return _VictionRandomize.Contract.SetOpening(&_VictionRandomize.TransactOpts, _opening)
}

// SetOpening is a paid mutator transaction binding the contract method 0xe11f5ba2.
//
// Solidity: function setOpening(bytes32 _opening) returns()
func (_VictionRandomize *VictionRandomizeTransactorSession) SetOpening(_opening [32]byte) (types.Transaction, error) {
	return _VictionRandomize.Contract.SetOpening(&_VictionRandomize.TransactOpts, _opening)
}

// SetSecret is a paid mutator transaction binding the contract method 0x34d38600.
//
// Solidity: function setSecret(bytes32[] _secret) returns()
func (_VictionRandomize *VictionRandomizeTransactor) SetSecret(opts *bind.TransactOpts, _secret [][32]byte) (types.Transaction, error) {
	return _VictionRandomize.contract.Transact(opts, "setSecret", _secret)
}

// SetSecret is a paid mutator transaction binding the contract method 0x34d38600.
//
// Solidity: function setSecret(bytes32[] _secret) returns()
func (_VictionRandomize *VictionRandomizeSession) SetSecret(_secret [][32]byte) (types.Transaction, error) {
	return _VictionRandomize.Contract.SetSecret(&_VictionRandomize.TransactOpts, _secret)
}

// SetSecret is a paid mutator transaction binding the contract method 0x34d38600.
//
// Solidity: function setSecret(bytes32[] _secret) returns()
func (_VictionRandomize *VictionRandomizeTransactorSession) SetSecret(_secret [][32]byte) (types.Transaction, error) {
	return _VictionRandomize.Contract.SetSecret(&_VictionRandomize.TransactOpts, _secret)
}

// VictionRandomizeSetOpeningParams is an auto generated read-only Go binding of transcaction calldata params
type VictionRandomizeSetOpeningParams struct {
	Param__opening [32]byte
}

// Parse SetOpening method from calldata of a transaction
//
// Solidity: function setOpening(bytes32 _opening) returns()
func ParseVictionRandomizeSetOpeningParams(calldata []byte) (*VictionRandomizeSetOpeningParams, error) {
	if len(calldata) <= 4 {
		return nil, fmt.Errorf("invalid calldata input")
	}

	_abi, err := abi.JSON(strings.NewReader(VictionRandomizeABI))
	if err != nil {
		return nil, fmt.Errorf("failed to get abi of registry metadata: %w", err)
	}

	out, err := _abi.Methods["setOpening"].Inputs.Unpack(calldata[4:])
	if err != nil {
		return nil, fmt.Errorf("failed to unpack setOpening params data: %w", err)
	}

	var paramsResult = new(VictionRandomizeSetOpeningParams)
	value := reflect.ValueOf(paramsResult).Elem()

	if value.NumField() != len(out) {
		return nil, fmt.Errorf("failed to match calldata with param field number")
	}

	out0 := *abi.ConvertType(out[0], new([32]byte)).(*[32]byte)

	return &VictionRandomizeSetOpeningParams{
		Param__opening: out0,
	}, nil
}

// VictionRandomizeSetSecretParams is an auto generated read-only Go binding of transcaction calldata params
type VictionRandomizeSetSecretParams struct {
	Param__secret [][32]byte
}

// Parse SetSecret method from calldata of a transaction
//
// Solidity: function setSecret(bytes32[] _secret) returns()
func ParseVictionRandomizeSetSecretParams(calldata []byte) (*VictionRandomizeSetSecretParams, error) {
	if len(calldata) <= 4 {
		return nil, fmt.Errorf("invalid calldata input")
	}

	_abi, err := abi.JSON(strings.NewReader(VictionRandomizeABI))
	if err != nil {
		return nil, fmt.Errorf("failed to get abi of registry metadata: %w", err)
	}

	out, err := _abi.Methods["setSecret"].Inputs.Unpack(calldata[4:])
	if err != nil {
		return nil, fmt.Errorf("failed to unpack setSecret params data: %w", err)
	}

	var paramsResult = new(VictionRandomizeSetSecretParams)
	value := reflect.ValueOf(paramsResult).Elem()

	if value.NumField() != len(out) {
		return nil, fmt.Errorf("failed to match calldata with param field number")
	}

	out0 := *abi.ConvertType(out[0], new([][32]byte)).(*[][32]byte)

	return &VictionRandomizeSetSecretParams{
		Param__secret: out0,
	}, nil
}
